### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by PallHaraldsson** [GenieFramework/StippleCharts.jl#2]
since master allows/<s>uses</s> Stipple 0.9?

For me this package downgraded DataStructures, and I wasn't even sure if important to your package or others, it just seem like you would want it at latest (and well pretty much all packages).

I realize I can use master, not sure all do. Is that usually the recommendation up to 1.0 version (e.g. not for Genie)?

There seems to be no breaking change to this package, but Stipple 0.9 is, does a breaking change in a dependency mean the using package should have a breaking version number? I guess it does if it requires it, in your case you allow older Stipple, but is that adviced?

**Comment by hhaensel** [comment]
Just tagged the new versions of Stipple, StippleUI and StippleCharts. Now we have to wait for the robot to register the versions.

**Comment by hhaensel** [comment]
All done
